services:

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marcusfontoura_wp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: '--default-storage-engine=InnoDB'

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - db

volumes:
  db_data:
    driver: local